name = "LifeDetection"
uuid = "6ef60fa5-8c1b-4d8d-8887-ac9953014983"
authors = ["Hailey Warner <hlwarner@stanford.edu>"]
version = "0.1.0"

[deps]
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
StatsPlots = "0.15.7"
